import { DarkTheme, DefaultTheme } from "@react-navigation/native";
import { Appearance } from "react-native";

const colorScheme = Appearance.getColorScheme()

export const theme = colorScheme == 'light' ? {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    infoText: 'rgba(0,0,0,0.67)',
    disabledText: 'rgba(0,0,0,0.33)',
    background: 'rgb(245,247,245)', 
    primary: '#333333',
    onPrimary: '#ffffff'
  }
} : {
  ...DarkTheme,
  colors: {
    ...DarkTheme.colors,
    infoText: 'rgba(255,255,255,0.67)',
    disabledText: 'rgba(255,255,255,0.33)',
    primary: '#ffffff',
    onPrimary: '#333333'
  }
}

export const text = {
  'en': {
    welcome: 'Welcome!',
    featuredCourses: 'Featured Courses',
    featuredWorkouts: 'Featured Workouts',
    sales: "Don't miss out",
    seeMore: 'See more',
    blogPosts: 'Blog Posts',
    workouts: 'Workouts',
    exercises: 'Exercises',
    courses: 'Courses',
    chooseEquipment: 'Choose equipment:',
    all: 'All',
    duration: 'Duration',
    dificulty: 'Dificulty',
    equpmentsRequired: 'Equipments required',
    description: 'Description',
    overview: 'Overview',
    buyCourseButton: 'BUY THE COURSE',
    profile: 'Profile',
    signOut: 'Sign Out',
    accountSettings: 'Account Settings',
    changePassword: 'Change Password',
    language: 'Language',
    privacy: 'Privacy',
    notifications: 'Notifications',
    appSettings: 'App Settings',
    customerSupport: 'Customer Support',
    termsConditions: 'Terms and Conditions',
    contact: 'Contact',
    socialMedia: 'Social Media',
    email: 'Email',
    password: 'Password',
    loginButton: 'LOGIN',
    noAccountQ: "Don't have an account?",
    signUp: "Sign Up",
    signUpButton: 'SIGN UP',
    forgotPasswordQ: 'Forgot pasword?',
    firstName: 'First Name',
    lastName: 'Last Name',
    confirmPassword: 'Confirm Password',
    alreadyAccountQ: 'Already have an account?',
    login: 'Login',
    resetPasswordButton: 'RESET PASSWORD',
    goBack: 'Go back',
    emailSendText: 'Check your email inbox to reset your password. Beware to check the spam or junk folder too, if you cannot found the email in inbox.',
    changeButton: 'CHANGE',
    oldPassword: 'Old Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    changePasswordButton: 'CHANGE PASSWORD',
    changeLanguage: 'Change Language',
    english: 'English',
    german: 'German',
    personalInformations: 'Personal Informations',
    noCourses: 'No courses to be shown.',
    deleteAccount: 'Delete Account'
  },
  'de': {
    welcome: 'Willkommen!',
    featuredCourses: 'Empfohlene Kurse',
    featuredWorkouts: 'Empfohlene Workouts',
    sales: 'Angebote',
    seeMore: 'Mehr anzeigen',
    blogPosts: 'Blog-Posts',
    workouts: 'Workouts',
    exercises: 'Übungen',
    courses: 'Kurse',
    chooseEquipment: 'Gerät auswählen:',
    all: 'Alle',
    duration: 'Dauer',
    dificulty: 'Schwierigkeit',
    equpmentsRequired: 'Erforderliche Geräte',
    description: 'Beschreibung',
    overview: 'Übersicht',
    buyCourseButton: 'DEN KURS KAUFEN',
    profile: 'Profil',
    signOut: 'Abmelden',
    accountSettings: 'Kontoeinstellungen',
    changePassword: 'Passwort ändern',
    language: 'Sprache',
    privacy: 'Datenschutz',
    notifications: 'Benachrichtigungen',
    appSettings: 'App Einstellungen',
    customerSupport: 'Kundenunterstützung',
    termsConditions: 'AGB',
    contact: 'Kontakt',
    socialMedia: 'Social Media',
    email: 'Email',
    password: 'Passwort',
    loginButton: 'ANMELDEN',
    noAccountQ: "Sie haben noch kein Konto?",
    signUp: "Registrieren",
    signUpButton: 'REGISTRIEREN',
    forgotPasswordQ: 'Passwort vergessen?',
    firstName: 'Vorname',
    lastName: 'Familienname',
    confirmPassword: 'Passwort bestätigen',
    alreadyAccountQ: 'Haben Sie bereits ein Konto?',
    login: 'Anmelden',
    resetPasswordButton: 'PASSWORT ZURÜCKSETZEN',
    goBack: 'Zurückgehen',
    emailSendText: 'Überprüfen Sie Ihren E-Mail-Posteingang, um Ihr Passwort zurückzusetzen. Achten Sie darauf, auch den Spam- oder Junk-Ordner zu überprüfen, wenn Sie die E-Mail nicht in Ihrem Posteingang finden.',
    changeButton: 'ÄNDERN',
    oldPassword: 'Altes Passwort',
    newPassword: 'Neues Passwort',
    confirmNewPassword: 'Neues Passwort bestätigen',
    changePasswordButton: 'PASSWORT ÄNDERN',
    changeLanguage: 'Sprache ändern',
    english: 'Englisch',
    german: 'Deutsch',
    personalInformations: 'Persönliche Informationen',
    noCourses: 'Es sind keine Kurse zu zeigen.',
    deleteAccount: 'Konto löschen'
  }
}
